
import { LanguageDictionary } from "./types";

export const APP_NAME = "AniAdda";

export const TRANSLATIONS: LanguageDictionary = {
  home: { en: "Home", bn: "হোম" },
  search: { en: "Search", bn: "খুঁজুন" },
  lists: { en: "My Lists", bn: "আমার লিস্ট" },
  profile: { en: "Profile", bn: "প্রোফাইল" },
  trending: { en: "Trending", bn: "জনপ্রিয়" },
  top: { en: "Top Rated", bn: "সেরা রেটিং" },
  topRated: { en: "Top Rated", bn: "সেরা রেটিং" },
  upcoming: { en: "Upcoming", bn: "আসছে" },
  seasonal: { en: "This Season", bn: "এই সিজন" },
  anime: { en: "Anime", bn: "এনিমে" },
  manga: { en: "Manga", bn: "মাঙ্গা" },
  manhwa: { en: "Manhwa", bn: "মানহওয়া" },
  manhua: { en: "Manhua", bn: "মানহুয়া" },
  hentai: { en: "Hentai", bn: "হেন্টাই" },
  doujinshi: { en: "Doujinshi", bn: "দোজিনশি" },
  ln: { en: "Light Novel", bn: "লাইট নোভেল" },
  lightNovel: { en: "Light Novel", bn: "লাইট নোভেল" },
  episodes: { en: "Episodes", bn: "পর্ব" },
  chapters: { en: "Chapters", bn: "অধ্যায়" },
  volumes: { en: "Volumes", bn: "ভলিউম" },
  score: { en: "Score", bn: "স্কোর" },
  progress: { en: "Progress", bn: "অগ্রগতি" },
  status: { en: "Status", bn: "অবস্থা" },
  save: { en: "Save", bn: "সংরক্ষণ" },
  cancel: { en: "Cancel", bn: "বাতিল" },
  watching: { en: "Watching", bn: "দেখছি" },
  reading: { en: "Reading", bn: "পড়ছি" },
  completed: { en: "Completed", bn: "সম্পন্ন" },
  planned: { en: "Planning", bn: "পরিকল্পনায়" },
  dropped: { en: "Dropped", bn: "বাদ দিয়েছি" },
  onHold: { en: "On Hold", bn: "স্থগিত" },
  all: { en: "All", bn: "সব" },
  welcome: { en: "Welcome back", bn: "স্বাগতম" },
  loading: { en: "Loading...", bn: "লোড হচ্ছে..." },
  noResults: { en: "No results found", bn: "কোন ফলাফল পাওয়া যায়নি" },
  addToCollection: { en: "Add to List", bn: "লিস্টে যোগ করুন" },
  editEntry: { en: "Update Progress", bn: "আপডেট করুন" },
  nextEp: { en: "Next Ep", bn: "পরের পর্ব" },
  total: { en: "Total", bn: "মোট" },
  synopsis: { en: "Synopsis", bn: "সারাংশ" },
  information: { en: "Information", bn: "তথ্য" },
  studios: { en: "Studios", bn: "স্টুডিও" },
  authors: { en: "Authors", bn: "লেখক" },
  genres: { en: "Genres", bn: "জনরা" },
  duration: { en: "Duration", bn: "সময়কাল" },
  rating: { en: "Rating", bn: "রেটিং" },
  source: { en: "Source", bn: "উৎস" },
  format: { en: "Format", bn: "ফরম্যাট" },
  relations: { en: "Related Media", bn: "সম্পর্কিত মিডিয়া" },
  back: { en: "Back", bn: "ফিরে যান" },
  filters: { en: "Filters", bn: "ফিল্টার" },
  type: { en: "Type", bn: "ধরন" },
  sortBy: { en: "Sort By", bn: "সাজান" },
  alphabetical: { en: "Alphabetical", bn: "বর্ণানুক্রমিক" },
  asc: { en: "Ascending", bn: "আরোহী" },
  desc: { en: "Descending", bn: "অবরোহী" },
  genre: { en: "Genre", bn: "জনরা" }
};

export const GENRES_LIST = [
  "Action", "Adventure", "Comedy", "Drama", "Ecchi", "Fantasy", 
  "Horror", "Mahou Shoujo", "Mecha", "Music", "Mystery", "Psychological", 
  "Romance", "Sci-Fi", "Slice of Life", "Sports", "Supernatural", "Thriller",
  "Hentai", "School", "Seinen", "Shoujo", "Shounen", "Josei", "Isekai", "Harem", 
  "Military", "Historical", "Police", "Samurai", "Space", "Super Power", 
  "Vampire", "Martial Arts", "Demons", "Parody", "Erotica", "Gore"
].sort();
